android_binary(
  name = 'rangzen',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:18',
  keystore = ':debug_keystore',
  deps = [
    '//java/org/denovogroup/rangzen:rangzen',
    '//res/org/denovogroup/rangzen:res',
  ],
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)

project_config(
  src_target = ':rangzen',
)
