// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/barathraghavan/code/rangzen/rangzen/buck-out/gen/proto-repo/compile_protobufs__srcs/RangzenMessage.proto
package org.denovogroup.rangzen.objects;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * Representation of a single Rangzen message with text and priority.
 */
public final class RangzenMessage extends Message {

  public static final String DEFAULT_TEXT = "";
  public static final Double DEFAULT_PRIORITY = 0D;

  /**
   * The message's text, as a String.
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String text;

  /**
   * The message's priority, as a double.
   */
  @ProtoField(tag = 2, type = DOUBLE, label = REQUIRED)
  public final Double priority;

  public RangzenMessage(String text, Double priority) {
    this.text = text;
    this.priority = priority;
  }

  private RangzenMessage(Builder builder) {
    this(builder.text, builder.priority);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RangzenMessage)) return false;
    RangzenMessage o = (RangzenMessage) other;
    return equals(text, o.text)
        && equals(priority, o.priority);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = text != null ? text.hashCode() : 0;
      result = result * 37 + (priority != null ? priority.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RangzenMessage> {

    public String text;
    public Double priority;

    public Builder() {
    }

    public Builder(RangzenMessage message) {
      super(message);
      if (message == null) return;
      this.text = message.text;
      this.priority = message.priority;
    }

    /**
     * The message's text, as a String.
     */
    public Builder text(String text) {
      this.text = text;
      return this;
    }

    /**
     * The message's priority, as a double.
     */
    public Builder priority(Double priority) {
      this.priority = priority;
      return this;
    }

    @Override
    public RangzenMessage build() {
      checkRequiredFields();
      return new RangzenMessage(this);
    }
  }
}
