android_binary(
  name = 'experimentalApp',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    '//java/org/denovogroup/rangzen:experimentalBackend',
    '//ui/Rangzen/src/org/denovogroup/rangzen:experimentalUI',
    '//ui/ViewPagerIndicator/src/com/viewpagerindicator:ViewPagerIndicator',
  ],
)
  
keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)

project_config(
  src_target = ':rangzen',
)
