android_resource(
  name = 'experimentalUIRes',
  res = 'res',
  package = 'org.denovogroup.rangzen',
  visibility = [ 'PUBLIC' ],
  deps = [
    '//ui/appcompat_v7_4/libs:android-support-v7-appcompat',
    '//ui/appcompat_v7_4:appcompatRes',
  ],
)

