android_resource(
  name = 'experimentalUIRes',
  res = 'res',
  package = 'org.denovogroup.rangzen',
  visibility = [ 'PUBLIC' ],
  deps = [
    '//ui/appcompat_v7_4/libs:android-support-v7-appcompat',
    '//ui/appcompat_v7_4:appcompatRes',
    '//ui/google-play-services_lib/libs:google-play-services',
    '//ui/google-play-services_lib:googlePlayServicesRes',
    '//libs:android-support-v4',
  ],
)

