android_library(
  name = 'experimental',
  srcs = glob(['*.java']),
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:android-support-v4',
    '//res/org/denovogroup/experimental:res',
  ],
)

project_config(
  src_target = ':experimental',
)
