android_library(
  name = 'experimental',
  srcs = [ 'MainActivity.java', 
           'MessageSendIntentService.java', 'Peer.java', 'PeerNetwork.java', 
           'RangzenService.java', 'PeerManager.java', 'WifiDirectSpeaker.java',
           'WifiDirectFrameworkGetter.java', ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:android-support-v4',
    '//res/org/denovogroup/experimental:res',
  ],
)

project_config(
  src_target = ':experimental',
)
