java_test(
  name = 'peerTest',
  srcs = ['PeerTest.java', ],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/experimental:experimental',
  ],
)
java_test(
  name = 'nullTest',
  srcs = ['NullTest.java'],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/experimental:experimental',
  ],
)
