robolectric_test(
  name = 'peerTest',
  srcs = ['PeerTest.java', ],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:robolectric-2.3-SNAPSHOT',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/experimental:experimental',
  ],
)

java_test(
  name = 'nullTest',
  srcs = ['NullTest.java'],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/experimental:experimental',
  ],
)

robolectric_test(
  name = 'nullRoboTest',
  srcs = ['NullRoboTest.java'],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//java/org/denovogroup/experimental:experimental',
    '//libs:robolectric-2.2',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
  ],
)

robolectric_test(
  name = 'rangzenServiceTest',
  srcs = ['RangzenServiceTest.java',],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/experimental:res',
  ],
  deps = [
    '//java/org/denovogroup/experimental:experimental',
    '//libs:robolectric-2.2',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//res/org/denovogroup/experimental:res',
  ],
)

robolectric_test(
  name = 'peerManagerTest',
  srcs = ['PeerManagerTest.java'],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/experimental:res',
  ],
  deps = [
    '//java/org/denovogroup/experimental:experimental',
    '//libs:robolectric-2.3-SNAPSHOT',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/experimental:experimental',
  ],
)

robolectric_test(
  name = 'wifiDirectSpeakerTest',
  srcs = ['WifiDirectSpeakerTest.java'],
  source_under_test = [ '//java/org/denovogroup/experimental:experimental' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/experimental:res',
  ],
  deps = [
    '//java/org/denovogroup/experimental:experimental',
    '//libs:robolectric-2.3-SNAPSHOT',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/experimental:experimental',
  ],
)
