android_library(
  name = 'rangzen',
  srcs = [ 'MainActivity.java', 
           'RangzenService.java',
           'Peer.java',
           'PeerNetwork.java',
           'HotspotPeerNetwork.java',
           'WifiDirectPeerNetwork.java',
           'PeerManager.java',
           'WifiDirectSpeaker.java',
           'WifiDirectFrameworkGetter.java',
           'BluetoothLESpeaker.java',
           'StorageBase.java' ,
            
  ],

  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:android-support-v4',
    '//res/org/denovogroup/rangzen:res',
  ],
)
