android_library(
  name = 'rangzen',
  srcs = [ 'MainActivity.java', 'Peer.java', 'PeerNetwork.java', 
           'RangzenService.java', 'PeerManager.java', 'StorageBase.java', 'WifiDirectSpeaker.java',
           'WifiDirectFrameworkGetter.java', ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:android-support-v4',
    '//res/org/denovogroup/rangzen:res',
  ],
)
