robolectric_test(
  name = 'peerTest',
  srcs = ['PeerTest.java', ],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:robolectric-2.3',
    '//libs:hamcrest-core-1.3',
    '//libs:mockito',
    '//java/org/denovogroup/rangzen:rangzen',
  ],
)

robolectric_test(
  name = 'locationStoreTest',
  srcs = ['LocationStoreTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/rangzen:res',
  ],
  deps = [
    '//libs:robolectric-2.3',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen:rangzen',
  ],
)

robolectric_test(
  name = 'messageStoreTest',
  srcs = ['MessageStoreTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/rangzen:res',
  ],
  deps = [
    '//libs:robolectric-2.3',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen:rangzen',
  ],
)

java_test(
  name = 'nullTest',
  srcs = ['NullTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen:rangzen',
  ],
)

robolectric_test(
  name = 'nullRoboTest',
  srcs = ['NullRoboTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//java/org/denovogroup/rangzen:rangzen',
    '//libs:robolectric-2.3',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
  ],
)

robolectric_test(
  name = 'rangzenServiceTest',
  srcs = ['RangzenServiceTest.java',],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/rangzen:res',
  ],
  deps = [
    '//java/org/denovogroup/rangzen:rangzen',
    '//libs:robolectric-2.3',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//res/org/denovogroup/rangzen:res',
  ],
)

# robolectric_test(
#   name = 'peerManagerTest',
#   srcs = ['PeerManagerTest.java'],
#   source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
#   visibility = [ 'PUBLIC' ],
#   resources = [
#     '//res/org/denovogroup/rangzen:res',
#   ],
#   deps = [
#     '//libs:robolectric-2.3',
#     '//libs:junit-4.11',
#     '//libs:hamcrest-core-1.3',
#     '//java/org/denovogroup/rangzen:rangzen',
#   ],
# )

robolectric_test(
  name = 'storageBaseTest',
  srcs = ['StorageBaseTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/rangzen:res',
  ],
  deps = [
    '//libs:robolectric-2.3',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen:rangzen',
  ],
)

robolectric_test(
  name = 'contactsGetterStorerTest',
  srcs = ['ContactsGetterStorerTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/rangzen:res',
  ],
  deps = [
    '//libs:robolectric-2.3',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen:rangzen',
  ],
)

robolectric_test(
  name = 'wifiDirectSpeakerTest',
  srcs = ['WifiDirectSpeakerTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen:rangzen' ],
  visibility = [ 'PUBLIC' ],
  resources = [
    '//res/org/denovogroup/rangzen:res',
  ],
  deps = [
    '//libs:robolectric-2.3',
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen:rangzen',
  ],
)
