android_library(
  name = 'zxing',
  srcs = glob(['**/*.java']),
  deps = [
    '//ui/zxing:res',
    '//libs:android-support-v4',
    '//ui/appcompat_v7_4/libs:android-support-v7-appcompat',
  ],
  visibility = [ 'PUBLIC' ],
)
