android_library(
  name = 'ViewPagerIndicator',
  srcs = [ 
    'CirclePageIndicator.java',
    'IconPageIndicator.java',
    'IconPagerAdapter.java',
    'IcsLinearLayout.java',
    'LinePageIndicator.java',
    'PageIndicator.java',
    'TabPageIndicator.java',
    'TitlePageIndicator.java',
    'UnderlinePageIndicator.java',
  ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//ui/ViewPagerIndicator:viewPagerIndicatorRes',
    '//libs:android-support-v4',
  ],
)
